name: Pull Request

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
jobs:
  validate:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Terraform # TODO Should probably push this down to Go
      uses: hashicorp/setup-terraform@v1
      with:
        # https://github.com/gruntwork-io/terratest/issues/706#issuecomment-733495166
        terraform_wrapper: false
    - uses: actions/cache@v3
      name: Cache plugin dir
      with:
        path: ~/.tflint.d/plugins
        key: ${{ matrix.os }}-tflint-${{ hashFiles('.tflint.hcl') }}
    - uses: terraform-linters/setup-tflint@v3
      name: Setup TFLint
      with:
        tflint_version: latest # v0.44.1
    #- name: Setup Go
    #  uses: actions/setup-go@v3
    #  with:
    #    go-version: '>=1.17.0'
    #- name: Setup Golang caches
    #  uses: actions/cache@v3
    #  with:
    #    path: |
    #      ~/.cache/go-build
    #      ~/go/pkg/mod
    #    key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
    #    restore-keys: |
    #      ${{ runner.os }}-golang-
    - name: Check Format
      run: make fmt
    - name: Lint
      run: make lint
    #- name: Run tests
    #  run: |
    #    make test